<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>field_password</name>
   <tag></tag>
   <elementGuidId>bac8d717-fd65-4359-b4b2-a9ae4bfd705e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a093b5a1-aefc-4b2a-bf63-e18a60f15411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>114d1b28-49a4-4ec9-ab96-580ac3e2389d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maximum-scale</name>
      <type>Main</type>
      <value>1.6</value>
      <webElementGuid>4d147854-fccc-451c-add1-9a103c6682e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>user-scalable</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>c7ee163a-0227-459e-b965-0d81d61821eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>24e46eff-e355-4afe-92e2-8a61f6211cd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-11/12 border-b bg-transparent focus:outline-none font-bold text-sm placeholder-gray-500 text-white border-gray-400 border-opacity-20</value>
      <webElementGuid>09f2c068-3483-4c70-8218-c8e318799a7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;bg-blue-1 flex flex-col min-h-screen text-white font-montserrat&quot;]/div[@class=&quot;vm--container&quot;]/div[@class=&quot;vm--modal modal-classes full-height mx-auto&quot;]/div[@class=&quot;text-white layout-login-wrapper&quot;]/form[@class=&quot;mb-6&quot;]/div[@class=&quot;border border-opacity-50 rounded-full px-7 py-3 mb-4&quot;]/div[@class=&quot;mb-4 input-signin&quot;]/label[1]/div[@class=&quot;relative&quot;]/input[@class=&quot;w-11/12 border-b bg-transparent focus:outline-none font-bold text-sm placeholder-gray-500 text-white border-gray-400 border-opacity-20&quot;]</value>
      <webElementGuid>ba56cb04-9601-41fc-9eb9-ca434b9109e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='password']</value>
      <webElementGuid>832429c6-2975-494d-bdad-320adfc79a32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[5]/div[2]/div/form/div[2]/div/label/div[2]/input</value>
      <webElementGuid>4c35d06a-5c92-4193-a0c9-868f61720d02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>44476f14-6a5c-40f5-ae27-95ea60ccfe81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password']</value>
      <webElementGuid>c458017c-9612-4150-94f1-603c0ca59fe5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
